using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace StrongId.SourceGenerators;

[Generator]
public class StrongIdJsonConverterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax c && c.BaseList is not null,
                transform: static (ctx, _) => GetTarget(ctx))
            .Where(static t => t is not null)
            .Collect();

        context.RegisterSourceOutput(candidates, static (spc, types) =>
        {
            var seen = new HashSet<string>();
            foreach (var type in types)
            {
                if (type is null) continue;
                var key = type.ToDisplayString();
                if (!seen.Add(key)) continue;
                Emit(spc, type);
            }
        });
    }

    private static INamedTypeSymbol? GetTarget(GeneratorSyntaxContext ctx)
    {
        var decl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(decl) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (!InheritsFromStrongIdBase(symbol))
        {
            return null;
        }

        if (!IsPartial(decl))
        {
            return null;
        }

        return symbol;
    }

    private static bool InheritsFromStrongIdBase(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.OriginalDefinition.ToDisplayString() == "StrongId.Base.StrongIdBase<T>")
            {
                return true;
            }
            current = current.BaseType;
        }
        return false;
    }

    private static bool IsPartial(ClassDeclarationSyntax decl)
    {
        foreach (var mod in decl.Modifiers)
        {
            if (mod.ValueText == "partial") return true;
        }
        return false;
    }

    private static void Emit(SourceProductionContext spc, INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();
        var name = symbol.Name;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }
        sb.AppendLine("[global::System.Text.Json.Serialization.JsonConverter(typeof(global::StrongId.Converters.StrongIdJsonConverter))]");
        sb.Append("partial class ").Append(name).Append(" : global::StrongId.Interfaces.IStrongIdFactory<").Append(name).AppendLine(">");
        sb.AppendLine("{");
        sb.Append("    private ").Append(name).AppendLine("() { }");
        sb.Append("    static ").Append(name).Append(" global::StrongId.Interfaces.IStrongIdFactory<").Append(name).Append(">.NewInstance(string value) => new ").Append(name).AppendLine("() { Value = value };");
        sb.AppendLine("}");

        var hint = (ns is null ? name : ns + "." + name) + ".StrongIdCtor.g.cs";
        spc.AddSource(hint, sb.ToString());
    }
}
