using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace StrongId.SourceGenerators;

[Generator]
public class StrongIdJsonConverterGenerator : IIncrementalGenerator
{
    private const string PrefixAttributeFullName = "StrongId.Attributes.StrongIdPrefixAttribute";
    private const string StrongIdBaseFullName = "StrongId.Base.StrongIdBase<T>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fromAttribute = context.SyntaxProvider.ForAttributeWithMetadataName(
                PrefixAttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax c && IsPartial(c),
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        var fromBase = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax c && IsPartial(c) && c.BaseList is not null,
                transform: static (ctx, _) => GetIfInheritsStrongIdBase(ctx))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!);

        var combined = fromAttribute.Collect().Combine(fromBase.Collect());

        context.RegisterSourceOutput(combined, static (spc, tuple) =>
        {
            var seen = new HashSet<string>();
            foreach (var type in tuple.Left.Concat(tuple.Right))
            {
                if (type is null) continue;
                var key = type.ToDisplayString();
                if (!seen.Add(key)) continue;
                Emit(spc, type);
            }
        });
    }

    private static bool IsPartial(ClassDeclarationSyntax decl)
    {
        foreach (var mod in decl.Modifiers)
        {
            if (mod.ValueText == "partial") return true;
        }
        return false;
    }

    private static INamedTypeSymbol? GetIfInheritsStrongIdBase(GeneratorSyntaxContext ctx)
    {
        var decl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(decl) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        return InheritsFromStrongIdBase(symbol) ? symbol : null;
    }

    private static bool InheritsFromStrongIdBase(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.OriginalDefinition.ToDisplayString() == StrongIdBaseFullName)
            {
                return true;
            }
            current = current.BaseType;
        }
        return false;
    }

    private static void Emit(SourceProductionContext spc, INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();
        var name = symbol.Name;
        var hasBase = InheritsFromStrongIdBase(symbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }
        sb.AppendLine("[global::System.Text.Json.Serialization.JsonConverter(typeof(global::StrongId.Converters.StrongIdJsonConverter))]");
        sb.Append("partial class ").Append(name).Append(" : ");
        if (!hasBase)
        {
            sb.Append("global::StrongId.Base.StrongIdBase<").Append(name).Append(">, ");
        }
        sb.Append("global::StrongId.Interfaces.IStrongIdFactory<").Append(name).AppendLine(">");
        sb.AppendLine("{");
        sb.Append("    private ").Append(name).AppendLine("() { }");
        sb.Append("    public static ").Append(name).Append(" NewInstance(string value) => new ").Append(name).AppendLine("() { Value = value };");
        sb.AppendLine("}");

        var hint = (ns is null ? name : ns + "." + name) + ".StrongIdCtor.g.cs";
        spc.AddSource(hint, sb.ToString());
    }
}
