using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace StrongId.SourceGenerators;

[Generator]
public class StrongIdJsonConverterGenerator : IIncrementalGenerator
{
    private const string PrefixAttributeFullName = "StrongId.Attributes.StrongIdPrefixAttribute";
    private const string StrongIdBaseFullName = "StrongId.Base.StrongIdBase<T>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fromAttribute = context.SyntaxProvider.ForAttributeWithMetadataName(
                PrefixAttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax c && IsPartial(c),
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        var fromBase = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax c && IsPartial(c) && c.BaseList is not null,
                transform: static (ctx, _) => GetIfInheritsStrongIdBase(ctx))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!);

        var combined = fromAttribute.Collect().Combine(fromBase.Collect());

        context.RegisterSourceOutput(combined, static (spc, tuple) =>
        {
            var seen = new HashSet<string>();
            foreach (var type in tuple.Left.Concat(tuple.Right))
            {
                if (type is null) continue;
                var key = type.ToDisplayString();
                if (!seen.Add(key)) continue;
                Emit(spc, type);
            }
        });
    }

    private static string? ReadSaltFromAttribute(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != PrefixAttributeFullName) continue;

            string? salt = null;
            var ctor = attr.ConstructorArguments;

            // Positional: (prefix, scheme, storage, salt)
            if (ctor.Length > 3 && ctor[3].Value is string s)
            {
                salt = s;
            }

            foreach (var named in attr.NamedArguments)
            {
                if (named.Key == "CustomSalt" && named.Value.Value is string ns)
                {
                    salt = ns;
                }
            }

            return salt;
        }

        return null;
    }

    private static bool IsPartial(ClassDeclarationSyntax decl)
    {
        foreach (var mod in decl.Modifiers)
        {
            if (mod.ValueText == "partial") return true;
        }
        return false;
    }

    private static INamedTypeSymbol? GetIfInheritsStrongIdBase(GeneratorSyntaxContext ctx)
    {
        var decl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(decl) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        return InheritsFromStrongIdBase(symbol) ? symbol : null;
    }

    private static bool InheritsFromStrongIdBase(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.OriginalDefinition.ToDisplayString() == StrongIdBaseFullName)
            {
                return true;
            }
            current = current.BaseType;
        }
        return false;
    }

    private static void Emit(SourceProductionContext spc, INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();
        var name = symbol.Name;
        var hasBase = InheritsFromStrongIdBase(symbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }
        sb.AppendLine("[global::System.Text.Json.Serialization.JsonConverter(typeof(global::StrongId.Converters.StrongIdJsonConverter))]");
        sb.Append("[global::System.ComponentModel.TypeConverter(typeof(global::StrongId.Converters.IdTypeConverter<").Append(name).AppendLine(">))]");
        sb.Append("partial class ").Append(name).Append(" : ");
        if (!hasBase)
        {
            sb.Append("global::StrongId.Base.StrongIdBase<").Append(name).Append(">, ");
        }
        sb.Append("global::StrongId.Interfaces.IStrongIdFactory<").Append(name).AppendLine(">");
        sb.AppendLine("{");
        sb.Append("    private ").Append(name).AppendLine("() { }");

        // Per-type opt-in: a non-null `salt:` argument on the attribute populates the
        // protected Salt on StrongIdBase via the same object-initializer pattern as Value.
        var customSalt = ReadSaltFromAttribute(symbol);
        sb.Append("    public static ").Append(name).Append(" NewInstance(string value) => new ").Append(name).Append("() { Value = value");
        if (customSalt is not null)
        {
            sb.Append(", Salt = \"").Append(EscapeStringLiteral(customSalt)).Append("\"");
        }
        sb.AppendLine(" };");

        sb.AppendLine("}");

        var hint = (ns is null ? name : ns + "." + name) + ".StrongIdCtor.g.cs";
        spc.AddSource(hint, sb.ToString());
    }

    private static string EscapeStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\r': sb.Append("\\r"); break;
                case '\n': sb.Append("\\n"); break;
                case '\t': sb.Append("\\t"); break;
                case '\0': sb.Append("\\0"); break;
                default: sb.Append(c); break;
            }
        }
        return sb.ToString();
    }
}
